# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-23 18:33
from __future__ import unicode_literals

import app.models
import app.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
# import smart_selects.db_fields


class Migration(migrations.Migration):

    replaces = [(b'app', '0001_initial'), (b'app', '0002_auto_20180603_1959'), (b'app', '0003_customuser_full_name'), (b'app', '0004_asha'), (b'app', '0005_auto_20180604_0102'), (b'app', '0006_auto_20180611_1118'), (b'app', '0007_auto_20180611_1359'), (b'app', '0008_auto_20180611_1459'), (b'app', '0009_auto_20180611_1710'), (b'app', '0010_contentcategory'), (b'app', '0011_cohort_status'), (b'app', '0012_cohort_author'), (b'app', '0013_remove_cohort_author'), (b'app', '0014_cohort_author'), (b'app', '0015_auto_20180613_0712'), (b'app', '0016_audiofile'), (b'app', '0017_content'), (b'app', '0018_auto_20180615_1001'), (b'app', '0019_textmessage'), (b'app', '0020_sendaudiotrailer'), (b'app', '0021_showfeedback'), (b'app', '0022_showrecording'), (b'app', '0023_auto_20180627_2251'), (b'app', '0024_auto_20180627_2303'), (b'app', '0025_show_qa'), (b'app', '0026_auto_20180718_1109'), (b'app', '0027_remove_show_qa'), (b'app', '0028_show_noofquestions'), (b'app', '0029_auto_20180722_2125'), (b'app', '0030_auto_20180723_0422'), (b'app', '0031_auto_20180723_0428')]

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('email', models.EmailField(default='DELHI', max_length=255, unique=True)),
                ('location', models.CharField(default='delhi', max_length=255)),
                ('staff', models.BooleanField(default=False)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phoneNumber', models.BigIntegerField(unique=True)),
                ('ashaID', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('YearOfJoining', models.IntegerField(blank=True, choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027)], null=True)),
                ('PhoneType', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=b'static/app/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to=b'auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to=b'auth.Permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohortID', models.CharField(max_length=100, unique=True)),
                ('broadcaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcastedBy', to='app.Asha')),
                ('listeners', models.ManyToManyField(blank=True, related_name='listenedBy', to=b'app.Asha')),
                ('status', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExpertID', models.CharField(max_length=100, unique=True)),
                ('FullName', models.CharField(max_length=100, unique=True)),
                ('phoneNumber', models.BigIntegerField(unique=True)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Content categories',
            },
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audioFor', models.CharField(choices=[(b'content', b'content'), (b'trailer', b'trailer'), (b'Q&A', b'Q&A')], max_length=100, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('file', models.FileField(max_length=200, null=True, upload_to=app.models.audioFilesPath, validators=[app.validators.validate_audiofile_extension])),
                ('localized', models.CharField(max_length=100, null=True, verbose_name=b'Localised Name')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentID', models.CharField(editable=False, max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name=b'Topic')),
                ('localized', models.CharField(max_length=100, null=True, verbose_name=b'Localised Name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ContentCategory')),
                ('files', models.ManyToManyField(to=b'app.AudioFile')),
            ],
            options={
                'verbose_name_plural': 'Content',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showID', models.CharField(editable=False, max_length=100, unique=True)),
                ('recording', models.FileField(blank=True, max_length=200, null=True, upload_to=b'static/Uploads/show_recordings/combined_recordings/', validators=[app.validators.validate_audiofile_extension])),
                ('STAT', models.BooleanField(default=False)),
                ('show_stats', models.FileField(blank=True, max_length=200, null=True, upload_to=b'static/Uploads/show_stats/')),
                ('timeOfAiring', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, b'Due'), (1, b'Done')], default=0)),
                ('QA1', models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QA1_audio', to='app.AudioFile')),
                ('QA2', models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QA2_audio', to='app.AudioFile')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ContentCategory')),
                ('cohort', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cohort')),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,  to='app.Content', verbose_name=b'topic')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='show',
            unique_together=set([('cohort', 'timeOfAiring')]),
        ),
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textMessage', models.TextField(max_length=1000, null=True)),
                ('additionalPhoneNumbers', models.TextField(blank=True, help_text=b'Add comma separated phone numbers. Please do not use any spaces in this field.', max_length=1000, null=True, validators=[django.core.validators.int_list_validator, app.validators.validate_phonenumbers_list])),
                ('recipientAshas', models.ManyToManyField(blank=True, to=b'app.Asha')),
            ],
        ),
        migrations.CreateModel(
            name='SendAudioTrailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(choices=[(b'listeners only', b'listeners only'), (b'broadcaster only', b'broadcaster only'), (b'broadcaster and listeners', b'broadcaster and listeners'), (b'none', b'none')], default=b'none', max_length=100)),
                ('additionalPhoneNumbers', models.TextField(blank=True, help_text=b'Add comma separated additional phone numbers. Please do not use any spaces in this field.', max_length=1000, null=True, validators=[django.core.validators.int_list_validator, app.validators.validate_phonenumbers_list])),
                ('timeAndDate', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, b'Not scheduled after last save'), (1, b'Scheduled')], default=0)),
                ('recipientAshas', models.ManyToManyField(blank=True, help_text=b'You may add additional Ashas here.', to=b'app.Asha', verbose_name=b'Other Ashas')),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Show')),
                ('trailer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.AudioFile')),
            ],
        ),
        migrations.CreateModel(
            name='ShowFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(help_text=b'Name of the person giving feedback.', max_length=100)),
                ('feedbackFile', models.FileField(max_length=200, null=True, upload_to=b'static/Uploads/show_feedback/', validators=[app.validators.validate_audiofile_extension])),
                ('textualFeedback', models.TextField(blank=True, max_length=1000, null=True)),
                ('show', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Show')),
            ],
        ),
        migrations.CreateModel(
            name='ShowRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordingFile', models.FileField(max_length=200, null=True, upload_to=b'static/Uploads/show_recordings/', validators=[app.validators.validate_audiofile_extension])),
                ('show', models.ForeignKey(help_text=b'Select a show from the dropdown', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Show')),
            ],
        ),
        migrations.AlterField(
            model_name='show',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Content', verbose_name=b'topic'),
        ),
        migrations.AddField(
            model_name='show',
            name='QA10',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QA10_audio', to='app.AudioFile'),
        ),
        migrations.AddField(
            model_name='show',
            name='QA3',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QA3_audio', to='app.AudioFile'),
        ),
        migrations.AddField(
            model_name='show',
            name='QA4',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QA4_audio', to='app.AudioFile'),
        ),
        migrations.AddField(
            model_name='show',
            name='QA5',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QA5_audio', to='app.AudioFile'),
        ),
        migrations.AddField(
            model_name='show',
            name='QA6',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QA6_audio', to='app.AudioFile'),
        ),
        migrations.AddField(
            model_name='show',
            name='QA7',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QA7_audio', to='app.AudioFile'),
        ),
        migrations.AddField(
            model_name='show',
            name='QA8',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QA8_audio', to='app.AudioFile'),
        ),
        migrations.AddField(
            model_name='show',
            name='QA9',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='QA9_audio', to='app.AudioFile'),
        ),
        migrations.AlterField(
            model_name='show',
            name='timeOfAiring',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='show',
            name='NoOfQuestions',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='active',
            new_name='superadmin',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='admin',
            new_name='superuser',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='staff',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
