# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-30 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'app', '0002_auto_20180823_1843'), (b'app', '0003_auto_20180825_2237'), (b'app', '0004_auto_20180825_2250'), (b'app', '0005_customuser_is_active'), (b'app', '0006_auto_20180826_0144'), (b'app', '0007_customuser_mail_sent'), (b'app', '0008_remove_show_prefeedback')]

    dependencies = [
        ('app', '0001_squashed_0031_auto_20180723_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='superadmin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='superuser',
        ),
        migrations.AddField(
            model_name='customuser',
            name='MA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='SA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='UA',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_Valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='show',
            name='preFeedback',
        ),
    ]
