# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 20:43
from __future__ import unicode_literals

import WebPortal.models
import WebPortal.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phoneNumber', models.BigIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)])),
                ('ashaID', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('yearOfJoining', models.IntegerField(blank=True, choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], null=True)),
                ('phoneType', models.CharField(blank=True, choices=[('basic', 'basic'), ('smartphone', 'smartphone')], max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/asha/photos/')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asha_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asha_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('file', models.FileField(max_length=200, null=True, upload_to=WebPortal.models.audioFilesPath, validators=[WebPortal.validators.validate_audiofile_extension])),
                ('audioFor', models.CharField(choices=[('content', 'content'), ('trailer', 'trailer'), ('expert_feedback', 'expert_feedback')], max_length=100, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audiofile_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audiofile_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohortID', models.CharField(editable=False, max_length=100, unique=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohort_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('broadcaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcastedBy', to='WebPortal.Asha')),
                ('listeners', models.ManyToManyField(blank=True, related_name='listenedBy', to='WebPortal.Asha')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohort_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentID', models.CharField(editable=False, max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
        ),
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contentcategory_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contentcategory_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name_plural': 'Content categories',
            },
        ),
        migrations.CreateModel(
            name='SendAudioTrailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(choices=[('listeners only', 'listeners only'), ('broadcaster only', 'broadcaster only'), ('broadcaster and listeners', 'broadcaster and listeners'), ('none', 'none')], default='none', max_length=100)),
                ('additionalPhoneNumbers', models.TextField(blank=True, help_text='Add comma separated additional phone numbers. Please do not use any spaces in this field.', max_length=1000, null=True, validators=[django.core.validators.int_list_validator, WebPortal.validators.validate_phonenumbers_list])),
                ('timeAndDate', models.DateTimeField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sendaudiotrailer_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('recipientAshas', models.ManyToManyField(blank=True, help_text='You may add additional Ashas here.', to='WebPortal.Asha')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showID', models.CharField(editable=False, max_length=100, unique=True)),
                ('recording', models.FileField(blank=True, max_length=200, null=True, upload_to='uploads/show_recordings/', validators=[WebPortal.validators.validate_audiofile_extension])),
                ('timeOfAiring', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(0, 'Due'), (1, 'Done')], default=0, editable=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='show_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebPortal.ContentCategory')),
                ('cohort', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebPortal.Cohort')),
                ('content', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.CASCADE, to='WebPortal.Content')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='show_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
        ),
        migrations.CreateModel(
            name='ShowFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person giving feedback.', max_length=100)),
                ('textualFeedback', models.TextField(blank=True, max_length=1000, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showfeedback_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('feedbackFile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebPortal.AudioFile')),
                ('show', models.ForeignKey(help_text='Select a show from the dropdown. Click on the pencil if you want to view the show.', null=True, on_delete=django.db.models.deletion.CASCADE, to='WebPortal.Show')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showfeedback_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
        ),
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textMessage', models.TextField(max_length=1000, null=True)),
                ('additionalPhoneNumbers', models.TextField(blank=True, help_text='Add comma separated phone numbers. Please do not use any spaces in this field.', max_length=1000, null=True, validators=[django.core.validators.int_list_validator, WebPortal.validators.validate_phonenumbers_list])),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='textmessage_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('recipientAshas', models.ManyToManyField(blank=True, to='WebPortal.Asha')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='textmessage_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
        ),
        migrations.AddField(
            model_name='sendaudiotrailer',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebPortal.Show'),
        ),
        migrations.AddField(
            model_name='sendaudiotrailer',
            name='trailer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WebPortal.AudioFile'),
        ),
        migrations.AddField(
            model_name='sendaudiotrailer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sendaudiotrailer_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.ContentCategory'),
        ),
        migrations.AddField(
            model_name='content',
            name='files',
            field=models.ManyToManyField(to='WebPortal.AudioFile'),
        ),
        migrations.AddField(
            model_name='content',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterUniqueTogether(
            name='show',
            unique_together=set([('cohort', 'timeOfAiring')]),
        ),
    ]
