# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 15:20
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('WebPortal', '0002_auto_20170614_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='content',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.CASCADE, to='WebPortal.Content', verbose_name='Topic'),
        ),
    ]
