# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPortal', '0003_auto_20170614_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name_plural': 'Content'},
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Topic'),
        ),
    ]
