# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 18:00
from __future__ import unicode_literals

import WebPortal.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPortal', '0005_showrecording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='recording',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='uploads/show_recordings/combined_recordings/', validators=[WebPortal.validators.validate_audiofile_extension]),
        ),
    ]
