# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPortal', '0008_auto_20170623_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='localized',
            field=models.CharField(max_length=100, null=True, verbose_name='Localised Name'),
        ),
    ]
