# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-09 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('WebPortal', '0010_show_show_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='contentToLink',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.CASCADE, to='WebPortal.Content', verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='asha',
            name='yearOfJoining',
            field=models.IntegerField(blank=True, choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027)], null=True),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='audioFor',
            field=models.CharField(choices=[('content', 'content'), ('trailer', 'trailer'), ('Q&A', 'Q&A')], max_length=100, null=True),
        ),
    ]
