# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-09 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPortal', '0011_auto_20180409_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='contentToLink',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='details',
            field=models.CharField(help_text='give details', max_length=100, null=True),
        ),
    ]
