# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-09 08:58
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('WebPortal', '0012_auto_20180409_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='details',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='contentToLink',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.CASCADE, to='WebPortal.Content', verbose_name='Topic'),
        ),
    ]
