# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-09 10:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebPortal', '0013_auto_20180409_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QAID', models.CharField(editable=False, max_length=100, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qas_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('content', models.ManyToManyField(to='WebPortal.Content')),
            ],
            options={
                'verbose_name_plural': 'QAs',
            },
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='contentToLink',
        ),
        migrations.AddField(
            model_name='qas',
            name='questionFile',
            field=models.ManyToManyField(to='WebPortal.AudioFile'),
        ),
        migrations.AddField(
            model_name='qas',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qas_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
    ]
