# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-09 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPortal', '0018_auto_20180409_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qas',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
