# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-09 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPortal', '0019_auto_20180409_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='qas',
            name='QAID',
            field=models.CharField(default=1, editable=False, max_length=100, unique=True),
        ),
    ]
