# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-10 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPortal', '0020_qas_qaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qas',
            name='QAID',
        ),
        migrations.AlterField(
            model_name='qas',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
