# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-10 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebPortal', '0024_auto_20180410_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='question1',
        ),
    ]
