# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-10 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebPortal', '0026_show_question1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='question1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebPortal.AudioFile'),
        ),
    ]
