# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-10 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebPortal', '0027_auto_20180410_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='question1',
            new_name='question_1',
        ),
    ]
