# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-10 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebPortal', '0029_auto_20180410_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='answer_1',
            new_name='answer1',
        ),
    ]
