# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-10 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebPortal', '0030_auto_20180410_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='answer1',
            new_name='answer_aud1',
        ),
        migrations.AddField(
            model_name='show',
            name='answer_2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='answer2_audio', to='WebPortal.AudioFile'),
        ),
        migrations.AddField(
            model_name='show',
            name='answer_3',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='answer3_audio', to='WebPortal.AudioFile'),
        ),
        migrations.AddField(
            model_name='show',
            name='question_2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='question2_audio', to='WebPortal.AudioFile'),
        ),
        migrations.AddField(
            model_name='show',
            name='question_3',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='question3_audio', to='WebPortal.AudioFile'),
        ),
    ]
