# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-10 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebPortal', '0031_auto_20180410_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='answer_aud1',
        ),
    ]
