# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-10 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebPortal', '0033_show_answer_aud1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='answer_aud1',
        ),
        migrations.AddField(
            model_name='show',
            name='answer_1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='answer1_audio', to='WebPortal.AudioFile'),
        ),
    ]
