# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-10 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebPortal', '0034_auto_20180410_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='answer_1',
            new_name='answer1',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='answer_2',
            new_name='answer2',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='answer_3',
            new_name='answer3',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='question_1',
            new_name='question1',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='question_2',
            new_name='question2',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='question_3',
            new_name='question3',
        ),
    ]
