# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-10 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebPortal', '0037_auto_20180410_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='question1',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question1_audio', to='WebPortal.AudioFile'),
        ),
    ]
